### ISSUE TITLE
don't see expected 'paststagedetails' on tasks

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#125]
when looking at tasks in success/failure state, they don't seem to have paststagedetails set at all. when looking at an in-progress task, i see much less of a log than i'm expecting. are we not properly round-tripping / appending to that log?

**Comment by mvdan** [comment]
I was looking into #88 and was also stumped by this. I didn't spend much time digging into it yet though.

**Comment by mvdan** [comment]
I'm looking into this further. The stages are there, and they get appended; here's what I see with a few debug logs (don't mind the broken timestamps, that's on me):

```
$ grep 'added stage' dealbot-controller.log 
added stage: 51383757511-07-19 02:19:06 +0100 BST "Miner is online"
added stage: 51383757512-01-02 20:35:41 +0000 GMT "Miner responds to query ask"
added stage: 51383757512-03-21 06:44:49 +0000 GMT "Miner meets price criteria"
added stage: 51383757512-05-08 23:54:17 +0100 BST "Importing data into Lotus"
added stage: 51383757513-01-08 21:08:09 +0000 GMT "Reserving client funds"
added stage: 51383760130-08-12 13:39:23 +0100 BST "Checking for deal acceptance"
```

But when finalized, I don't see the same past stages. Debugging some more.

**Comment by mvdan** [comment]
It gets weirder. When we fetch the task from the database, PastStageDetails is never there in the raw dagjson. And when we store the dagjson back, there's just one past stage in the list - which at least makes sense, since we append one element to an empty list.

And when we go to finalize the task, PastStageDetails is absent, just like it is in all the Update queries.

This doesn't seem like an IPLD problem to me, because looking at the dagjson bytes, it looks good. And the append also seems to be working well. So it seems to be the database layer that's making us forget the PastStageDetails list.

I've pushed my debugging code to https://github.com/filecoin-project/dealbot/tree/debug-past-stages, and I'm attaching dealbot-controller.log from a run of the second integration test on that branch.
[dealbot-controller.log](https://github.com/filecoin-project/dealbot/files/6516155/dealbot-controller.log)

@gammazero could you please help me debug this? You know the SQL code better than me, and currently I'm a bit stuck. I can also do some pair programming/debugging in an hour or so if you're up for it.

**Comment by gammazero** [comment]
Confirmed every status/state update is being written to DB.  When the final status shows up I query task history to log all items.  However, it looks like there is a failure to read task history:
```
Could not get task history: "SQL logic error: no such table: task_status_ledger (1)
```

I also see another error in the controller log that I did not notice before:
```
dealbot-controller.log:2021-05-20T20:04:05.026Z	ERROR	controller	controller/tasks.go:110	popTask failed: backend	{"err": "SQL logic error: no such table: drained_workers (1)"}
```

I am guessing these are responsible, so fixing now.

**Comment by willscott** [comment]
that potentially implies there's a mismatch at
https://github.com/filecoin-project/dealbot/blob/main/controller/state/statedb.go#L398

Can we reconstruct the full history into one task at the point we ask to finalize it?

Finalize assumes all the previous stages have been collected into `paststagedetails` - the question is why they aren't

**Comment by gammazero** [comment]
@mvdan I think the problem is indicated by this place in your debug logs:
```
skip stage false true
saving task {
	"UUID": "f265bac2-2be8-4258-a8e1-20ffa4fafd02",
	"Status": 3,
	"WorkedBy": "d1bca999",
	"Stage": "StorageDealProposalAccepted",
```
Notice that the `Status` has changed to `3`, but the `Stage` has remained at `StorageDealProposalAccepted`.  The means that the final status update is getting skipped because the filter is only looking for a changes in `Stage` not in `Status`

If this reasoning is correct, then the necessary change is to also look for a change in `Status` here:
https://github.com/filecoin-project/dealbot/blob/main/tasks/model.go#L250

**Comment by gammazero** [comment]
@willscott 
> Can we reconstruct the full history into one task at the point we ask to finalize it?

Yes, I think all the necessary info is there.  It seems like constructing the task from history in DB is easier than maintaining all the task update logic and allows the update logic/filtering to exist in one place.

> Finalize assumes all the previous stages have been collected into `paststagedetails` - the question is why they aren't

The final state missing might be explained by my previous comment to @mvdan, but it looks like the rest are certainly getting updated in the task.  Still looking for the break between what is stored in the task and what gets written to DB.

**Comment by gammazero** [comment]
I instrumented `statedb.Update()` to call a version of @mvdan's debug code.  Looks like `task.UpdateTask(req)` is destroying the `PastStageDetails` portion of the task that was read from the database.

The first `Update` that saves stage info in the task looks like this:
```
------------------------------------------------
===> DATA FROM PREVIOUS SAVE (task read from DB)
>>>> PastStageDetails does not exist

===> DATA THAT SHOULD HAVE BEEN SAVED (in updatedTask)
>>>> recorded stages: 1
stage 0: 2021-05-21 01:19:52.683034289 +0000 UTC "Miner is online"
  stage 0 log 0: 2021-05-21 01:19:52.678964085 +0000 UTC "Tipset successfully fetched"
  stage 0 log 1: 2021-05-21 01:19:52.681145729 +0000 UTC "Miner Info successfully fetched"
  stage 0 log 2: 2021-05-21 01:19:52.681994235 +0000 UTC "Miner address validated"
  stage 0 log 3: 2021-05-21 01:19:52.683034289 +0000 UTC "Connected to miner"

===> DATA THAT WAS SAVED (task after update written to DB)
>>>> recorded stages: 1
stage 0: 2021-05-21 01:19:52.683034289 +0000 UTC "Miner is online"
  stage 0 log 0: 2021-05-21 01:19:52.678964085 +0000 UTC "Tipset successfully fetched"
  stage 0 log 1: 2021-05-21 01:19:52.681145729 +0000 UTC "Miner Info successfully fetched"
  stage 0 log 2: 2021-05-21 01:19:52.681994235 +0000 UTC "Miner address validated"
  stage 0 log 3: 2021-05-21 01:19:52.683034289 +0000 UTC "Connected to miner"
```
- The first section shows when the task is first read from the DB [here](https://github.com/filecoin-project/dealbot/blob/main/controller/state/statedb.go#L355). 
- The second section shows what the updatedTask looks like [here](https://github.com/filecoin-project/dealbot/blob/main/controller/state/statedb.go#L367)
- The third section shows what the task looks like after querying it again from the DB, after the transaction completes, and is done [here - code not shown](https://github.com/filecoin-project/dealbot/blob/main/controller/state/statedb.go#L367)

The next time `Update` is called, the data from the previous update is present... good... but then as soon as the `updatedTask` is created [here](https://github.com/filecoin-project/dealbot/blob/main/controller/state/statedb.go#L367), that data is gone.  Here is the debug output:
```
------------------------------------------------
===> DATA FROM PREVIOUS SAVE (task read from DB)
>>>> recorded stages: 1
stage 0: 2021-05-21 01:19:52.683034289 +0000 UTC "Miner is online"
  stage 0 log 0: 2021-05-21 01:19:52.678964085 +0000 UTC "Tipset successfully fetched"
  stage 0 log 1: 2021-05-21 01:19:52.681145729 +0000 UTC "Miner Info successfully fetched"
  stage 0 log 2: 2021-05-21 01:19:52.681994235 +0000 UTC "Miner address validated"
  stage 0 log 3: 2021-05-21 01:19:52.683034289 +0000 UTC "Connected to miner"

===> DATA THAT SHOULD HAVE BEEN SAVED (in updatedTask)
>>>> PastStageDetails does not exist

===> DATA THAT WAS SAVED (task after update written to DB)
>>>> PastStageDetails does not exist
```
 The task, now with no stage history, is saved to the DB.
