### ISSUE TITLE
a dealbot daemon with a single worker polls for more work while doing a deal

### ISSUE THREAD

**Issue by mvdan** [filecoin-project/dealbot#160]
If you run the second integration test via `bash integration_tests/02_controller_daemon.sh`, while the deal is being made (which takes multiple minutes), the controller gets spammed with pop-task requests every five seconds:

```
dealbot-daemon.log: 2021-05-28T15:48:30.529+0100        INFO    engine  tasks/storage_deal.go:298       Deal status     {"cid": "bafyreibekranctfmu4r4f3djo4tix4uhcusqn3ptejs47qoverehc56fsi", "piece": "baga6ea4seaqnvupw3dnivjfy5wdz4wfr7u35lkqkrwtb22joj2xwz6nnjuxocki", "state": "StorageDealAwaitingPreCommit", "message": "", "provider": "f01000"}
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:48:35 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:48:40 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:48:45 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:48:50 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:48:55 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-controller.log: 127.0.0.1 - - [28/May/2021:15:49:00 +0100] "POST /pop-task HTTP/1.1" 204 0
dealbot-daemon.log: 2021-05-28T15:49:02.023+0100        INFO    engine  tasks/storage_deal.go:298       Deal status     {"cid": "bafyreibekranctfmu4r4f3djo4tix4uhcusqn3ptejs47qoverehc56fsi", "piece": "baga6ea4seaqnvupw3dnivjfy5wdz4wfr7u35lkqkrwtb22joj2xwz6nnjuxocki", "state": "StorageDealSealing", "message": "", "provider": "f01000"}
```

This feels wrong. The second integration test runs with a single worker goroutine, and it's clearly busy doing a task, so it should not be attempting to pick up a second one.

**Comment by willscott** [comment]
it does look like the engine polls for tasks regardless of whether it can take on additional work at the moment:
https://github.com/filecoin-project/dealbot/blob/main/engine/engine.go#L102

**Comment by gammazero** [comment]
The behavior observed was not a defect.  Tasks that are run immediately are sent to the worker(s) to run, without waiting for the task to complete, and then another task is popped and given to another worker.  This is done until all workers are busy, resulting in popping one more task than there are workers.

If scheduled tasks are popped, and these do not run immediately, then any number of these can be popped and added to the scheduler since they do not cause workers to be busy.

With PR #170 a new task is popped only if there is an available worker.
