### ISSUE TITLE
Integration test runs in CI

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#36]
would be good to have sanity checks run to give us confidence in deploys

**Comment by nonsense** [comment]
The test I just added at https://github.com/filecoin-project/dealbot/pull/38 covers the integration with Lotus. I think we should certainly run it as part of CI, so that we know when/if we hit issues with Lotus - at least on devnets.

I am not sure we want to add tests right now for the controller and the daemon, as I expect we will change them a lot in the coming 3-4 days.

**Comment by nonsense** [comment]
This is mostly ready at this stage, however also somewhat flaky :(

1. `devnet` needs some improvements, as it occasionally fails.
2. Making deals with a `devnet` sometimes hits race conditions in Lotus.

**Comment by willscott** [comment]
this is happening now :+1:
