### ISSUE TITLE
Persistance for active deals

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#5]
The process should have a way to track the deals it has in flight, so that if it is restarted / re-deployed it can continue tracking them.

There are a couple options on the top of my head to manage this persistence:
* we could have the process run with access to a persistent volume / storage location where this in-flight information is stored.
* we could structure this 'state' object to remained synced with a driving 'orchestrator' program we expect to eventually exist
  * for instance: the orchestrator in asking for a deal can assign a uuid to the request. once a deal id or state object exists for it, the dealbot can response to save that state object with the uuid. If the orchestrator later asks the bot about a request uuid and the bot has been redeployed ad doesn't know about it, it can request the state back from the orchestrator and resume where it left off.  Other designs may turn out preferable / easier

**Comment by acruikshank** [comment]
A fairly simple solution would be to keep all the state on the dealbot server (coordinator). A dealbot client sends an ID (wallet address?) to the the server when it requests a task. The server tracks that this deal is in progress with this client. If the client gets restarted, it requests a new task and the server tells it that it has a task in progress, and it starts tracking progress for that deal rather than starting a new one.

The lotus API supports this well for storage deals, since you can fetch the history of a deal at any point in the process. I'm not so sure about retrievals deals.

The server (coordinator) would still need to persist the tasks and their status.
